// <auto-generated />
using System;
using AutoSale.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoSale.Vehicles.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutoSaleDbContext))]
    [Migration("20260908041314_AddVehicleReservationsAndCatalogOutbox")]
    partial class AddVehicleReservationsAndCatalogOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoSale.Domain.Catalog.CatalogOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_version");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("ix_catalog_outbox_lease_expiration");

                    b.HasIndex("VehicleId", "VehicleVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_outbox_vehicle_version");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "CreatedAtUtc")
                        .HasDatabaseName("ix_catalog_outbox_pending");

                    b.ToTable("catalog_outbox", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_outbox_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_catalog_outbox_vehicle_version", "vehicle_version > 0");
                        });
                });

            modelBuilder.Entity("AutoSale.Domain.Reservations.VehicleReservation", b =>
                {
                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<string>("ColorSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color_snapshot");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("MakeSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("make_snapshot");

                    b.Property<string>("ModelSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_snapshot");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price_snapshot");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleVersionSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_version_snapshot");

                    b.Property<short>("YearSnapshot")
                        .HasColumnType("smallint")
                        .HasColumnName("year_snapshot");

                    b.HasKey("SaleId");

                    b.HasIndex("VehicleId", "CreatedAtUtc")
                        .HasDatabaseName("ix_vehicle_reservations_vehicle_created");

                    b.ToTable("vehicle_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_reservations_price_positive", "price_snapshot > 0");

                            t.HasCheckConstraint("ck_vehicle_reservations_terminal_timestamp", "(status = 'Reserved' AND confirmed_at_utc IS NULL AND released_at_utc IS NULL) OR (status = 'Confirmed' AND confirmed_at_utc IS NOT NULL AND released_at_utc IS NULL) OR (status = 'Released' AND confirmed_at_utc IS NULL AND released_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicle_reservations_version", "vehicle_version_snapshot > 0");
                        });
                });

            modelBuilder.Entity("AutoSale.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ReservationSaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_sale_id");

                    b.Property<Guid?>("SoldSaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sold_sale_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Price", "Id")
                        .HasDatabaseName("ix_vehicles_status_price_id");

                    b.ToTable("vehicles", null, t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_price_positive", "price > 0");

                            t.HasCheckConstraint("ck_vehicles_status_references", "(status = 'Available' AND reservation_sale_id IS NULL AND sold_sale_id IS NULL) OR (status = 'Reserved' AND reservation_sale_id IS NOT NULL AND sold_sale_id IS NULL) OR (status = 'Sold' AND reservation_sale_id IS NULL AND sold_sale_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicles_version", "version > 0");

                            t.HasCheckConstraint("ck_vehicles_year", "year >= 1886");
                        });
                });

            modelBuilder.Entity("AutoSale.Domain.Catalog.CatalogOutbox", b =>
                {
                    b.HasOne("AutoSale.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoSale.Domain.Reservations.VehicleReservation", b =>
                {
                    b.HasOne("AutoSale.Domain.Vehicles.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
